import Head from 'next/head'
import LeftBar from '../components/LeftBar'
import RightBar from '../components/RightBar'
import Content from '../components/Content'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
    <div className={styles.blocker}>
      <p>Please view in desktop</p>
    </div>
    <div className={styles.container}>
      
        <div className={styles.topBar}>
          Lorem Ipsum is simply dummy text of the printing
        </div>
        <div className={styles.main}>
          <Head>
            <title>Dashboard</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <div className={styles.sideBarLeft}>
            <LeftBar />
          </div>
          <div className={styles.center}>
            <Content />
          </div>
          <div className={styles.sideBarRight}>
            <RightBar />
          </div>
        </div>

    </div>
    </>
  )
}
